sudo: required
language: minimal
install:
- wget -c https://releases.hashicorp.com/vagrant/2.1.2/vagrant_2.1.2_x86_64.deb
- sudo dpkg -i vagrant_2.1.2_x86_64.deb
script:
- vagrant plugin install vagrant-aws
