---
- name: Install Apache 2
  apt:
    name: apache2
    update_cache: yes
- name: Config Apache logs
  template:
    src: apache-logs.conf
    dest: /etc/apache2/conf-available/{{ conf }}
    owner: root
    group: root
    mode: 0644
- name: Enable new config
  file:
    src: ../conf-available/{{conf}}
    dest: /etc/apache2/conf-enabled/{{ conf }}
    owner: root
    group: root
    state: link
  notify: Restart Apache 2