---
- hosts: jenkins
  become: yes
  gather_facts: no
  tasks:
  - name: Install apt-transport-https (required for the apt_repository task)
    apt:
      name: apt-transport-https
      update_cache: yes
  - name: Install Oracle JDK 1.8.0_151 (required for Jenkins installation)
    include_tasks: oracle-java8-installation.yml
    tags:
      - java8-installation
  - name: Install Jenkins 2.73.3
    include_tasks: jenkins-installation.yml
    tags:
      - jenkins-installation
