---
- hosts: monitor
  become: yes
  tasks:
  - name: Install required packages
    apt:
      name: '{{item}}'
      update_cache: yes
    with_items:
      - apt-transport-https
      - python-setuptools
    tags:
      - installation
  - name: Install required Python modules
    easy_install:
      name: '{{item}}'
    with_items:
      - urllib3
      - pyOpenSSL
      - ndg-httpsclient
      - pyasn1
  - name: Install InfluxDB
    include_tasks: influxdb-installation.yml
    tags:
      - installation
      - influxdb-installation
  - name: Install Grafana 4.6.2
    include_tasks: grafana-installation.yml
    tags:
      - installation
      - grafana-installation
  - name: Install Ansible
    include_tasks: ansible-installation.yml
    tags:
      - installation
      - ansible-installation
  - name: Configure monitoring
    include_tasks: monitoring-configuration.yml
    tags:
      - configuration
