---
- hosts: monitor
  become: yes
  gather_facts: no
  tasks:
  - name: Install apt-transport-https (required for the apt_repository task)
    apt:
      name: apt-transport-https
      update_cache: yes
    tags:
      - installation
  - name: Install InfluxDB
    include_tasks: influxdb-installation.yml
    tags:
      - installation
      - influxdb-installation
  - name: Install Grafana 4.6.2
    include_tasks: grafana-installation.yml
    tags:
      - installation
      - grafana-installation
  - name: Install Ansible
    include_tasks: ansible-installation.yml
    tags:
      - installation
      - ansible-installation
  - name: Configure monitoring
    include_tasks: monitoring-configuration.yml
    tags:
      - configuration
