---
- hosts: monitor
  become: yes
  gather_facts: no
  tasks:
  - name: Install apt-transport-https (required for the apt_repository task)
    apt:
      name: apt-transport-https
      update_cache: yes
  - name: Install InfluxDB
    include_tasks: influxdb-installation.yml
  - name: Install Grafana
    include_tasks: grafana-installation.yml
  - name: Install Ansible
    include_tasks: ansible-installation.yml
