---
- hosts: monitor
  become: yes
  tasks:
  - name: Install required Ubuntu packages
    apt:
      name: '{{item}}'
      update_cache: yes
    with_items:
      - apt-transport-https
      - python-setuptools
    tags:
      - installation
  - name: Install PIP
    easy_install:
      name: pip
    tags:
      - installation
  - name: Install ndg-httpsclient (required Python module)
    pip:
      name: ndg-httpsclient
    tags:
      - installation
  - name: Install InfluxDB
    include_tasks: influxdb-installation.yml
    tags:
      - installation
      - influxdb-installation
  - name: Install Grafana 4.6.2
    include_tasks: grafana-installation.yml
    tags:
      - installation
      - grafana-installation
  - name: Install Ansible 2.4.1.0
    include_tasks: ansible-installation.yml
    tags:
      - installation
      - ansible-installation
  - name: Configure monitoring
    include_tasks: monitoring-configuration.yml
    tags:
      - configuration
