---
- hosts: localhost
  connection: local
  gather_facts: false
  vars_prompt:
    - name: "aws_region"
      prompt: "AWS Region"
      default: "sa-east-1"
      private: no
  tasks:
  - name: Gather facts about EC2 instances managed by Vagrant
    ec2_instance_facts:
      region: '{{aws_region}}'
      filters:
        instance.group-name: vagrant
    register: ec2_instance_facts_result
  - name: Save ec2 instances inventory file (part 1)
    template:
      src: ec2_hosts_template
      dest: '{{aws_region}}/ec2_hosts'
  - name: Save ec2 instances inventory file (part 2)
    lineinfile:
      path: '{{aws_region}}/ec2_hosts'
      insertafter: '^\[ec2_instances\]$'
      line: '{{item}}'
    with_items: '{{ec2_instance_facts_result|json_query("instances[*].public_ip_address")}}'
