---
dependency:
  name: galaxy
driver:
  name: ec2
lint:
  name: yamllint
platforms:
  - name: jenkins
    region: eu-west-2
    image: ami-0ef56f2737e9e6767
    instance_type: t2.micro
    vpc_subnet_id: subnet-1cb17175
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: aws
verifier:
  name: testinfra
  directory: ../tests
  lint:
    name: flake8
