---
- name: Create the target directory if it doesn't exist
  file:
    path: "{{ params[ansible_hostname].target }}"
    state: directory
- name: Install unzip
  apt:
    name: unzip
    update_cache: true
  when: params[ansible_hostname].url is match(".*\.zip$")
- name: Unarchive from url
  unarchive:
    src: "{{ params[ansible_hostname].url }}"
    dest: "{{ params[ansible_hostname].target }}"
    remote_src: true
